routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

// Users
Route::get( 'list/users', 'UserController@index' )->name('user-list');
Route::get( 'single/user/{id}', 'UserController@show' )->name('user-single');
Route::get( 'update/user/{id}', 'UserController@edit' )->name('user-edit');


Route::get('/', function () {
    return view('welcome');
});

// Bookmarks
Route::get( '/list/bookmarks', 'BookmarkController@index' )->name('bookmark-list')->middleware( 'auth' );
Route::get( '/new/bookmark', 'BookmarkController@create' )->name('bookmark-create')->middleware( 'auth' );
Route::post( '/new/bookmark', 'BookmarkController@store' )->name('bookmark-store')->middleware( 'auth' );
Route::get( '/update/bookmark/{id}', 'BookmarkController@edit' )->name('bookmark-edit')->middleware( 'auth' );
Route::put( '/update/bookmark/{id}', 'BookmarkController@update' )->name('bookmark-update')->middleware( 'auth' );
Route::delete( '/delete/bookmark/{id}', 'BookmarkController@destroy' )->name('bookmark-destroy')->middleware( 'auth' );
Route::get( '/single/bookmark/{id}', 'BookmarkController@show' )->name('bookmark-single');
Route::post( '/addcomment/bookmark/{id}', 'BookmarkController@add_comment' )->name( 'bookmark-add-comment' )->middleware( 'auth' );
Route::post( '/addvote/bookmark', 'BookmarkController@add_vote' )->name('bookmark-add-vote');
Route::post( '/search/bookmark', 'BookmarkController@search')->name('bookmark-search');

// Groups
Route::get( '/list/groups', 'GroupController@index' )->name('group-list')->middleware( 'auth' );
Route::get( '/new/group', 'GroupController@create' )->name('group-create')->middleware( 'auth' );
Route::post( '/new/group', 'GroupController@store' )->name('group-store')->middleware( 'auth' );
Route::get( '/update/group/{id}', 'GroupController@edit' )->name('group-edit')->middleware( 'auth' );
Route::put( '/update/group/{id}', 'GroupController@update' )->name('group-update')->middleware( 'auth' );
Route::delete( '/delete/group/{id}', 'GroupController@destroy' )->name('group-destroy')->middleware( 'auth' );
Route::get( '/single/group/{id}', 'GroupController@show' )->name( 'group-single' )->middleware( 'auth' );
Route::delete( '/remove-user/group/{id}/user/{id_user}', 'GroupController@update' )->name( 'group-remove-user' )->middleware( 'auth', 'IsAdmin' );
Route::post( '/search/group', 'GroupController@search')->name('group-search');

// Discussions
Route::get( 'list/discussions/group/{id_group}', 'DiscussionController@index' )->name('discussion-list')->middleware( 'auth' );
Route::get( 'new/discussion', 'DiscussionController@create' )->name('discussion-create')->middleware( 'auth' );
Route::post( 'new/discussion', 'DiscussionController@store' )->name('discussion-store')->middleware( 'auth' );
Route::get( 'update/discussion/{id}', 'DiscussionController@edit' )->name('discussion-edit')->middleware( 'auth' );
Route::put( 'update/discussion/{id}', 'DiscussionController@update' )->name('discussion-update')->middleware( 'auth' );
Route::get( 'single/discussion/{id}', 'DiscussionController@show' )->name('discussion-show')->middleware( 'auth' );
Route::delete( 'delete/discussion/{id}', 'DiscussionController@destroy' )->name('discussion-destroy')->middleware( 'auth' );
Route::post( 'search/users/discussion/{id}', 'DiscussionController@searchusers' )->name('search-users-discussion');
Route::post( 'add/user/{id_user}/discussion/{id_discussion}', 'DiscussionController@add_user_discussion' )->name('add-user-discussion');
Route::delete( 'remove/user/{id_user}/discussion/{id_discussion}', 'DiscussionController@remove_user_discussion' )->name('remove-user-discussion');
Route::get( 'list/users/discussions/{id}', 'DiscussionController@index_user_discussion' )->name('list-users-discussion');


// Messages
Route::get( 'list/messages', 'MessageController@index' )->name('message-list')->middleware( 'auth' );
Route::get( 'new/message', 'MessageController@create' )->name('message-create')->middleware( 'auth' );
Route::post( 'new/message/discussion/{id}', 'MessageController@store' )->name('message-store')->middleware( 'auth' );
Route::get( 'single/message/{$id}', 'MessageController@show' )->name('message-signle')->middleware( 'auth' );
Route::delete( 'delete/message/{$id}', 'MessageController@destroy' )->name('message-destroy')->middleware( 'auth' );

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model {
    
    public function bookmark() {
        
        return $this->belongsTo('App\Bookmark');
        
    }
    
    public function user() {
        
        return $this->belongsTo('App\User');
        
    }
    
    public function getCreatedAtAttribute( $date ) {
        $date = new \Carbon\Carbon( $date );
        
        return $date->format( 'd/m/Y à H:i' );
    }
    
}

resources/views/single/bookmark.blade.php
@extends('template')


@section('content')

<div class="panel panel-primary">
    <input id="id_bookmark" type="hidden" value="{{ $bookmark->id }}">
    <input id="id_user" type="hidden" value="{{ Auth::user()->id }}">
    <div class="panel-heading">
        <h2>{{ $bookmark->name }}</h2>
        <div class="flex-end">
            
            <div class="align-right" style="margin-right: 15px;">
                <div>Nombre de vote : <span id="nb_vote">{{ intval( $bookmark->nb_vote ) }}</span></div>
                <div>Nombre de cliques: <span id="id_clics">{{ intval( $bookmark->nb_vues ) }}</span></div>
            </div>
            
            <div class="btn-group">
            @auth
                <button id="button_vote" class="btn btn-success btn-hover" data-toggle="tooltip" data-placement="bottom" title="Vous avez déjà voté pour ce Boukmark">
                    <span class="glyphicon glyphicon-thumbs-up"></span>
                    <span class="cache-hover">J'aime</span>
                </button>
            @endauth
            @if( $canEdit )

                <a class="btn btn-primary btn-hover" href='{{ route('bookmark-update', $bookmark->id ) }}'>
                    <span class="glyphicon glyphicon-cog"></span>
                    <span class="cache-hover">Mettre à jour</span>
                </a>
                <button class="btn btn-danger btn-hover">
                    <span class="glyphicon glyphicon-remove"></span>
                    <span class="cache-hover">Supprimer</span>
                </button>
            @endif
            </div>

            
                
            
        </div>
    </div>
    
    <div class="panel-body">
        <p><strong>Description :</strong> {{ $bookmark->description }}</p>
        @if( $bookmark->type === 'url' )
        
            <strong>Url :</strong> <a href="{{ $bookmark->url }}" class="btn btn-link">{{ $bookmark->url }}</a>
        
        @elseif( $bookmark->type === 'text' )
        
            <p><strong>Contenus :</strong> {{ $bookmark->content }}</p>
        
        @endif
    </div>
</div>

@if( count( $comments ) == 0 )
<div class="well well-sm">
        Pas encore de commentaire...
</div>
@else

    @foreach( $comments as $comment)

    <div class="well well-sm">
        <div class="comment-head">{{ ucfirst( $comment->user->name ) }} a écrit le {{ $comment->createdAt }} :</div>
        {{ $comment->content }}
    </div>

    @endforeach
@endif

@auth
    {!! Form::open( [ 'route' => [ 'bookmark-add-comment', $bookmark->id ] ] ) !!}

    {{ Form::hidden( 'id_user', Auth::user()->id ) }}
    {{ Form::hidden( 'id_bookmark', $bookmark->id ) }}
    
    <div class="form-group" id="form-bm-content">
        {{ Form::label('content-comment', "Commentaire", ['class' => 'control-label']) }}
        {{ Form::textarea('content-comment', null, ['class' => 'form-control', 'rows' => '3']) }}
    </div>

    <div class="form-group">
        {{ Form::submit('Commenter', ['class' => 'btn btn-primary']) }}
    </div>


    {!! Form::close() !!}
@endauth

@stop

@section('scripts')


<script type="text/javascript">

    
    $("#button_vote").on("click", function() {
        $.ajax({
            url: '/addvote/bookmark',
            type: 'POST',
            data: 
            {
                id_bookmark: $("#id_bookmark").val(),
                id_user: $("#id_user").val()
        
            },
            success: function(retour) {
                if( retour === true ) {
                    let nb_vote = Number( $("#nb_vote").html() );
                    $("#nb_vote").html( nb_vote + 1 );
                }
                else {
                    alert('Vous avez déjà voté pour ce Bookmark');
                }
            }   
        });
    });

</script>

@stop

resources/views/single/discussion.blade.php
<?php
use App\Group;
use App\Discussion;
$user = Auth::user();

$group = $discussion->group()->first();
$users = $discussion->users()->get();
$user_discussions = $user->discussions()->get();
$messages = $discussion->messages()->get();
$group_dsc = $group->discussion()->first();

?>


@extends('template')

@section('aside-no-fix')

<!-- Action discussions -->
<div class="panel panel-danger">
    
    <div class="panel-heading">
        
        <h2> Discussions </h2>
        
    </div>
    
    <div class="panel-body">
        
        <div class="list-group">
            
            <a href="{{ route( 'group-single', $group->id ) }}" class="list-group-item">Groupe</a>
            
            <a href="{{ route( 'list-users-discussion', $discussion->id ) }}" class="list-group-item">Inviter un utilisateur</a>

        </div>
        
    </div>
    
</div>

<!-- Liste des membres dans la discussion en cour -->
<div class="panel panel-warning">
    
    <div class="panel-heading">
        
        <h2> Users de la discussion </h2>
        
    </div>
    
    <div class="panel-body">
        
        <div class="list-group">
            @foreach( $users as $user )
            
                <a href="#" class="list-group-item">{{ $user->name }}</a>
                    
            @endforeach
        </div>
        
    </div>
    
</div>

<!-- Si c'est un groupe personnel alors on affiche ses discussions -->
@if ( Group::isPersonalGroup( $group->id ) )
    <!-- Mes discussions -->
    <div class="panel panel-success">

        <div class="panel-heading">

            <h2> Mes discussions </h2>

        </div>

        <div class="panel-body">

            <div class="list-group">
            @foreach( $user_discussions as $discussion )
            
            <a href="{{ route( 'discussion-show', $discussion->id ) }}" class="list-group-item">{{ $discussion->name }}</a>
                    
            @endforeach
            </div>   

        </div>

    </div>
@else
    <!-- Conversation du groupe -->
    <div class="panel panel-success">

        <div class="panel-heading">

            <h2> Converstation du groupe </h2>

        </div>

        <div class="panel-body">

            <div class="list-group">
            
            <a href="{{ route( 'discussion-show', $group_dsc->id ) }}" class="list-group-item">{{ $group_dsc->name }}</a>
                    
            </div>   

        </div>

    </div>
@endif

@endsection


@section('content')

<div class="panel panel-primary">
    
    <div class="panel-heading">

        <h1> {{ $discussion->name }} </h1>
        
    </div>
    
    
    <div class="panel-body">
        @if ( Discussion::isEmpty( $discussion->id ) )
                <p> Il n'y a pas de messages. </p>
        @else
            @foreach( $messages as $message )
                <div class="msg">
                    <p style="text-decoration: underline;">De : {{ $message->user()->first()->name }} </p>
                    <p>Message : {{ $message->message }} </p>
                    <span class="time-right">Le : {{ $message->created_at }}</span>
                </div>
            @endforeach
        @endif
    </div>
    
    <div class="panel-footer">
        
        {!! Form::open([ 'method' => 'POST', 'route' => [ 'message-store', $discussion->id ] ]) !!}
        <div class="form-group">
                {{ Form::label('subject-msg', "Entrez le sujet de votre message", ['class' => 'control-label']) }}
                {{ Form::text('subject-msg', null ,  ['class' => 'form-control']) }}
        </div>
        <textarea name="message-msg" class="form-control" rows="3"></textarea><br>
        <button type="submit" class="btn btn-success">Envoyer</button>
        
        {!! Form::close() !!}
        
        
    </div>
    
</div>

@endsection

resources/views/single/group.blade.php
<?php
use App\Group;
$user = Auth::user();

/**
 * Discussion du groupe
 */
$group_dsc = $group->discussion()->first();

?>


@extends('template')

@section('aside-no-fix')

<!-- Action groupe -->
<div class="panel panel-danger">
    
    <div class="panel-heading">
        
        <h2> Gérer groupe </h2>
        
    </div>
    
    <div class="panel-body">
        
        <div class="list-group">
            <a href="{{ route( 'bookmark-create' ) }}" class="list-group-item">Publier un bookmark</a>
            <a href="{{ route( 'discussion-show', $group_dsc->id ) }}" class="list-group-item">Discussion</a>
            
            @if ( $user && $group->isAdmin($user->id) )
                
                <!-- Si ce n'est pas un groupe personnel -->
                @if( ! Group::isPersonalGroup($group->id) )
                    <a href="{{ route( 'discussion-edit', $group_dsc->id ) }}" class="list-group-item">Gérer la conversation de groupe</a>
                    <a href="#" class="list-group-item">Inviter un utilisateur</a>
                @endif

                <a href="{{ route( 'group-update', $group->id ) }}" class="list-group-item">Gérer mon groupe</a>
            
            @endif
            
        </div>
        
    </div>
    
</div>


<!-- Description -->
<div class="panel panel-success">
    
    <div class="panel-heading">
        
        <h2>Description du groupe</h2>
        
    </div>
    
    <div class="panel-body">
        
        <p>
            
            {{ $group->description }}
            
        </p>    
            
    </div>
    
</div>

@if ( ! Group::isPersonalGroup( $group->id ) )
<!-- Membres -->
<div class="panel panel-warning">
    
    <div class="panel-heading">
        
        <h2> Membres </h2>
        
    </div>
    
    <div class="panel-body">
        
        <div class="list-group">
            @foreach( $group->users as $user )
            
                <a href="#" class="list-group-item">{{ $user->name }}</a>
                    
            @endforeach
        </div>
        
    </div>
    
</div>
@endif

@endsection


@section('content')

<div class="panel panel-primary">
    
    <div class="panel-heading">

        <h1>{{ $group->name }}</h1>
        
    </div>
    
    
    <!-- Arborescence Bm -->
    <div class="panel-body">
        
        
        
    </div>
    
    <div class="panel-footer">
        
        
        
    </div>
    
</div>

@endsection